version: '3'
services:
  postfix:
    image: juanluisbaptiste/postfix
    environment:
      MYHOSTNAME: ${DOMAIN_NAME}
    volumes:
      - ./postfix:/etc/postfix
    ports:
      - "25:25"
      - "587:587"
    networks:
      - mail
  dovecot:
    image: dovecot/dovecot
    volumes:
      - ./dovecot:/etc/dovecot
    ports:
      - "143:143"
      - "993:993"
    networks:
      - mail
  gophish:
    image: gophish/gophish
    volumes:
      - ./gophish:/root/.gophish
    ports:
      - "3333:3333"
      - "8083:80"
    networks: 
      - mail
networks:
  mail:
