version: '3'
services:
  postfix:
    image: postfix:latest
    environment:
      MYHOSTNAME: ${DOMAIN_NAME}
    volumes:
      - ./postfix:/etc/postfix
    ports:
      - "25:25"
      - "587:587"
  dovecot:
    image: dovecot:latest
    volumes:
      - ./dovecot:/etc/dovecot
    ports:
      - "143:143"
      - "993:993"
