version: '3'
services:
  postfix:
    image: wailram/postfix
    environment:
      SMTP_SERVER: ${IP} 
      SERVER_HOSTNAME: ${DOMAIN_NAME}
      DESTINATION: ${DESTINATION}
      USERNAME_ACCOUNT: ${USERNAME_ACCOUNT}
      PASSWORD_ACCOUNT: ${PASSWORD_ACCOUNT}
    ports:
      - "25:25"
      - "587:587"
    networks:
      - mail
  dovecot:
    image: dovecot/dovecot
    ports:
      - "143:143"
      - "993:993"
    networks:
      - mail
  gophish:
    image: gophish/gophish
    volumes:
      - ./gophish:/root/.gophish
    ports:
      - "3333:3333"
      - "8083:80"
    networks: 
      - mail
networks:
  mail:
